## Hotel Booking Cancellation Prediction (Feature Engineering + ML)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("booking.csv")

In [3]:
df.head()

,Booking_ID,number of adults,number of children,number of weekend nights,number of week nights,type of meal,car parking space,room type,lead time,market segment type,repeated,P-C,P-not-C,average price,special requests,date of reservation,booking status
0,INN00001,1,1,2,5,Meal Plan 1,0,Room_Type 1,224,Offline,0,0,0,88.00,0,10/2/2015,Not_Canceled
1,INN00002,1,0,1,3,Not Selected,0,Room_Type 1,5,Online,0,0,0,106.68,1,11/6/2018,Not_Canceled
2,INN00003,2,1,1,3,Meal Plan 1,0,Room_Type 1,1,Online,0,0,0,50.00,0,2/28/2018,Canceled
3,INN00004,1,0,0,2,Meal Plan 1,0,Room_Type 1,211,Online,0,0,0,100.00,1,5/20/2017,Canceled
4,INN00005,1,0,1,2,Not Selected,0,Room_Type 1,48,Online,0,0,0,77.00,0,4/11/2018,Canceled

In [4]:
df.shape

(36285, 17)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36285 entries, 0 to 36284
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Booking_ID                36285 non-null  object
 1   number of adults          36285 non-null  int64
 2   number of children        36285 non-null  int64
 3   number of weekend nights  36285 non-null  int64
 4   number of week nights     36285 non-null  int64
 5   type of meal              36285 non-null  object
 6   car parking space         36285 non-null  int64
 7   room type                 36285 non-null  object
 8   lead time                 36285 non-null  int64
 9   market segment type       36285 non-null  object
 10  repeated                  36285 non-null  int64
 11  P-C                       36285 non-null  int64
 12  P-not-C                   36285 non-null  int64
 13  average price             36285 non-null  float64
 14  special requests          36285 non-null  int64
 15  date of reservation       36285 non-null  object
 16  booking status            36285 non-null  object
dtypes: float64(1), int64(10), object(6)
memory usage: 4.7+ MB

In [6]:
import re

df['reservation_date'] = df['date of reservation'].apply(
    lambda x: re.split(r'[-/]', str(x))[1]
)

In [7]:
import re

df['reservation_month'] = df['date of reservation'].apply(
    lambda x: re.split(r'[-/]', str(x))[1]
)

In [8]:
df['reservation_year'] = df['date of reservation'].apply(
    lambda x: re.split(r'[-/]', str(x))[2]
)

In [9]:
# df.head()
df.drop("date of reservation",axis=1,inplace=True)

In [10]:
df['reservation_date']=df['reservation_date'].astype(int)
df['reservation_month']=df['reservation_month'].astype(int)
df['reservation_year']=df['reservation_year'].astype(int)

In [12]:
df['booking status'].unique()

array(['Not_Canceled', 'Canceled'], dtype=object)

In [13]:
df['market segment type'].unique()

array(['Offline', 'Online', 'Corporate', 'Aviation', 'Complementary'],
      dtype=object)

In [14]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['booking status']=le.fit_transform(df['booking status'])

In [15]:
df = pd.get_dummies(
    df,
    columns=['market segment type'],
    dtype=int
)

In [16]:
df.head(10)

,Booking_ID,number of adults,number of children,number of weekend nights,number of week nights,type of meal,car parking space,room type,lead time,repeated,...,special requests,booking status,reservation_date,reservation_month,reservation_year,market segment type_Aviation,market segment type_Complementary,market segment type_Corporate,market segment type_Offline,market segment type_Online
0,INN00001,1,1,2,5,Meal Plan 1,0,Room_Type 1,224,0,...,0,1,2,2,2015,0,0,0,1,0
1,INN00002,1,0,1,3,Not Selected,0,Room_Type 1,5,0,...,1,1,6,6,2018,0,0,0,0,1
2,INN00003,2,1,1,3,Meal Plan 1,0,Room_Type 1,1,0,...,0,0,28,28,2018,0,0,0,0,1
3,INN00004,1,0,0,2,Meal Plan 1,0,Room_Type 1,211,0,...,1,0,20,20,2017,0,0,0,0,1
4,INN00005,1,0,1,2,Not Selected,0,Room_Type 1,48,0,...,0,0,11,11,2018,0,0,0,0,1
5,INN00006,1,0,0,2,Meal Plan 2,0,Room_Type 1,346,0,...,1,0,13,13,2016,0,0,0,1,0
6,INN00007,1,1,1,4,Meal Plan 1,0,Room_Type 1,34,0,...,1,1,15,15,2017,0,0,0,0,1
7,INN00008,3,0,1,3,Meal Plan 1,0,Room_Type 4,83,0,...,1,1,26,26,2018,0,0,0,0,1
8,INN00009,1,1,0,4,Meal Plan 1,0,Room_Type 1,121,0,...,1,1,6,6,2018,0,0,0,1,0
9,INN00010,2,0,0,5,Meal Plan 1,0,Room_Type 4,44,0,...,3,1,18,18,2018,0,0,0,0,1

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36285 entries, 0 to 36284
Data columns (total 23 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Booking_ID                         36285 non-null  object
 1   number of adults                   36285 non-null  int64
 2   number of children                 36285 non-null  int64
 3   number of weekend nights           36285 non-null  int64
 4   number of week nights              36285 non-null  int64
 5   type of meal                       36285 non-null  object
 6   car parking space                  36285 non-null  int64
 7   room type                          36285 non-null  object
 8   lead time                          36285 non-null  int64
 9   repeated                           36285 non-null  int64
 10  P-C                                36285 non-null  int64
 11  P-not-C                            36285 non-null  int64
 12  average price                      36285 non-null  float64
 13  special requests                   36285 non-null  int64
 14  booking status                     36285 non-null  int64
 15  reservation_date                   36285 non-null  int64
 16  reservation_month                  36285 non-null  int64
 17  reservation_year                   36285 non-null  int64
 18  market segment type_Aviation       36285 non-null  int64
 19  market segment type_Complementary  36285 non-null  int64
 20  market segment type_Corporate      36285 non-null  int64
 21  market segment type_Offline        36285 non-null  int64
 22  market segment type_Online         36285 non-null  int64
dtypes: float64(1), int64(19), object(3)
memory usage: 6.4+ MB

In [19]:
# df['type of meal'].unique()
# df['room type'].unique()
df['Booking_ID'].unique()

array(['INN00001', 'INN00002', 'INN00003', ..., 'INN36284', 'INN36285',
       'INN36286'], shape=(36285,), dtype=object)

In [20]:
df = pd.get_dummies(
    df,
    columns=['type of meal'],
    dtype=int
)

In [21]:
df = pd.get_dummies(
    df,
    columns=['room type'],
    dtype=int
)

In [22]:
df.drop('Booking_ID', axis=1, inplace=True)

In [24]:
# Remove duplicate booking records
df = df.drop_duplicates()
df=df.drop_duplicates()

In [25]:
# df.duplicated().sum()

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.preprocessing import StandardScaler

In [27]:
X=df.drop("booking status",axis=1)
y=df['booking status']

In [28]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [29]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [30]:
LR=LogisticRegression()
DT=DecisionTreeClassifier()
RF=RandomForestClassifier()
LR.fit(X_train_scaled,y_train)
DT.fit(X_train,y_train)
RF.fit(X_train,y_train)
LR_ypred=LR.predict(X_test_scaled)
DT_ypred=DT.predict(X_test)
RF_ypred=RF.predict(X_test)

In [31]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
results=[]
models={
    'LogisticRegression':LR,
    'DecisionTreeClassifier':DT,
    'RandomForestClassifier':RF
}
predictions={
    'LogisticRegression':LR_ypred,
    'DecisionTreeClassifier':DT_ypred,
    'RandomForestClassifier':RF_ypred
}

for name in models:
    results.append([
        name,
        accuracy_score(y_test,predictions[name]),
        precision_score(y_test,predictions[name]),
        recall_score(y_test,predictions[name]),
        f1_score(y_test,predictions[name])
    ])

In [32]:
comparison_df=pd.DataFrame(results,columns=["Model","Accuracy_Score","Precision_score","Recall_Score","F1_score"
                                           ])

In [33]:
comparison_df.sort_values(by='F1_score', ascending=False)

,Model,Accuracy_Score,Precision_score,Recall_Score,F1_score
2,RandomForestClassifier,0.844645,0.871381,0.917453,0.893824
0,LogisticRegression,0.804653,0.833954,0.906393,0.868666
1,DecisionTreeClassifier,0.784849,0.857854,0.836795,0.847194

Among the three machine learning models, the Random Forest Classifier achieved the best performance with the highest accuracy, precision, recall, and F1-score. Therefore, it is selected as the final model for predicting hotel booking cancellations.

In [34]:
param_grid={
    'n_estimators':[20,30,10,5],
    'min_samples_split':[20,30,10,3],
    'max_depth':[10,20,50,80,40]
}

In [35]:
grid = GridSearchCV(
    RF,
    param_grid,
    scoring='accuracy',
    cv=3,
)

In [36]:
grid.fit(X_train,y_train)

GridSearchCV(cv=3, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [10, 20, 50, 80, 40],
                         'min_samples_split': [20, 30, 10, 3],
                         'n_estimators': [20, 30, 10, 5]},
             scoring='accuracy')

In [37]:
grid.best_params_

{'max_depth': 20, 'min_samples_split': 20, 'n_estimators': 30}

In [38]:
grid.best_score_

np.float64(0.8504325390718667)

In [39]:
best_rf = grid.best_estimator_

y_pred = best_rf.predict(X_test)

In [40]:
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))

Accuracy : 0.8509901941934244
Precision: 0.8711392405063291
Recall   : 0.9282438629619638
F1 Score : 0.8987854251012146

In [41]:
print(grid.best_estimator_)

RandomForestClassifier(max_depth=20, min_samples_split=20, n_estimators=30)

In [42]:
print(type(grid.best_estimator_))

<class 'sklearn.ensemble._forest.RandomForestClassifier'>

In [43]:
import joblib

In [44]:
joblib.dump(best_rf,'hotel_booking_cancellation_model.joblib')

['hotel_booking_cancellation_model.joblib']

In [45]:
import os

print(os.getcwd())

C:\Users\KEERTHANA.N\ML (python)